# Generated by Django 5.0.2 on 2024-04-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Head Coach', 'Head Coach'), ('Sports Administrator', 'Sports Administrator')], default='Manager', max_length=50)),
                ('contact_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('game_type', models.CharField(choices=[('League game', 'League game'), ('Friendly game', 'Friendly game'), ('Tournament game', 'Tournament game')], default='League game', max_length=30)),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Draw', 'Draw')], default='Win', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=30)),
                ('dob', models.DateTimeField()),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('player_game', models.CharField(choices=[('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Netball', 'Netball')], default='Volleyball', max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('jersey_no', models.IntegerField()),
                ('medical_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Head Coach', 'Head Coach'), ('Assistant Coach', 'Assistant Coach'), ('Manager', 'Manager'), ('Fitness Coach', 'Fitness Coach'), ('Team Doctor', 'Team Doctor')], default='Head Coach', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[('National league', 'National league'), ('Corporate league', 'Corporate league')], default='National league', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('injury_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_occured', models.DateField()),
                ('body_part', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('Moderate', 'Moderate'), ('Intense', 'Intense')], default='Moderate', max_length=50)),
                ('estimated_recovery_date', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_halfs_played', models.CharField(max_length=100)),
                ('goals_scored', models.IntegerField(null=True)),
                ('saves_made', models.IntegerField(null=True)),
                ('attack_kills', models.IntegerField(null=True)),
                ('block_kills', models.IntegerField(null=True)),
                ('cover_saves', models.IntegerField(null=True)),
                ('receptions_delivered', models.IntegerField(null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('training_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Game Situations', 'Game situations'), ('Physical Fitness', 'Physical Fitness'), ('Mental Fitness', 'Mental Fitness')], default='Game Situations', max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Observations', 'Observations'), ('Complaint', 'Complaint')], default='Observations', max_length=30)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.administrator')),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.match')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
                ('staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.staff')),
                ('training_session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=30)),
                ('match_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
                ('staff_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.staff')),
                ('training_session_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingsession')),
            ],
        ),
    ]
