# Generated by Django 5.0.2 on 2024-04-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_player_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact_no',
            field=models.CharField(default=256700654924, max_length=50),
            preserve_default=False,
        ),
    ]
