# Generated by Django 5.0.2 on 2024-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_match_date_time_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='date_time',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
