# Generated by Django 5.0.2 on 2024-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_playerfeedback1_playerfeedback2_stafffeedback1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerfeedback1',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='playerfeedback2',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='stafffeedback1',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='stafffeedback2',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
