# Generated by Django 5.0.2 on 2024-04-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_playerfeedback1_date_playerfeedback2_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance1',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=30)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
                ('staff_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.staff')),
                ('training_session_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance2',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=30)),
                ('match_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.match')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
